### ISSUE TITLE
Homepage background color issue

### ISSUE THREAD

**Issue by Siddikpatel** [Siddikpatel/Textapp#1]
The thing is when I set the background color property in the App.js file, it works fine but if I enable dark mode and then turn the light mode again, the background remains black and the container shows color, even though I have set document property globally.

So, I have removed the property temporarily from global scope and it is only modified when I toggle the dark mode switch. 

What I want is, that colors should change according to the theme in whole application. By the way ignore the about,js file theme. It's currently under development.

P.S. I use bootstrap and I've used dismissable alert but the the alert close button doesn't look styled. Would be cool if you can fix that too. Also, If you don't see anything except navbar when you first visit the website, just click on home. I am still new to github pages so I need to set up how to show other components

**Comment by Nayanp760** [comment]
Assign me this issue
